USE ITAssetManagement;
GO

CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FullName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(150) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE Assets (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    AssetTag NVARCHAR(50) NOT NULL UNIQUE,
    AssetName NVARCHAR(100) NOT NULL,
    Category NVARCHAR(100) NOT NULL,
    Brand NVARCHAR(100) NULL,
    Model NVARCHAR(100) NULL,
    SerialNumber NVARCHAR(100) NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'Available',
    AssignedTo NVARCHAR(100) NULL,
    PurchaseDate DATE NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE()
);
GO